### ISSUE TITLE
gcp auth provider missing

### ISSUE THREAD

**Issue by jjo** [bitnami/sealed-secrets#45]
@santinoncs reports:
```
$ kubeseal <mysecret.json >mysealedsecret.json
panic: No Auth Provider found for name "gcp"
```

**Comment by anguslees** [comment]
Which version of kubeseal is this?  I think this was fixed in #41 -- which I note has not yet made it into a release (oops).

@santinoncs It would be great if you could test a fresh kubeseal build from master (`go get github.com/bitnami/sealed-secrets/cmd/kubeseal`), and let me know if it does/doesn't work for you with gcp.
If that works for you, then I'll cut a proper release including that functionality.

**Comment by santinoncs** [comment]
It works.

**Comment by anguslees** [comment]
[v0.4.0](https://github.com/bitnami/sealed-secrets/releases/tag/v0.4.0) released yesterday that includes the auth plugins.
Thanks to @santinoncs and @jjo for their work on this issue.
