### ISSUE TITLE
Garbage collection errors when deleting the secret before sealedsecret

### ISSUE THREAD

**Issue by arapulido** [bitnami/sealed-secrets#54]
Steps to reproduce:

* Create a sealedsecret in the cluster
* kubectl delete the secret (not the sealed one)
* kubectl delete the sealedsecret

The controller will keep trying to delete the associate secret as part of the garbage collection, but will err continuously as the secret was already deleted:

```
2017/09/18 09:23:56 Updating default/mysecret
2017/09/18 09:33:16 SealedSecret default/mysecret has gone, deleting Secret
2017/09/18 09:33:16 Error updating default/mysecret, will retry: secrets "mysecret" not found
2017/09/18 09:33:16 SealedSecret default/mysecret has gone, deleting Secret
2017/09/18 09:33:16 Error updating default/mysecret, will retry: secrets "mysecret" not found
2017/09/18 09:33:16 SealedSecret default/mysecret has gone, deleting Secret
2017/09/18 09:33:16 Error updating default/mysecret, will retry: secrets "mysecret" not found
2017/09/18 09:33:16 SealedSecret default/mysecret has gone, deleting Secret
2017/09/18 09:33:16 Error updating default/mysecret, will retry: secrets "mysecret" not found
2017/09/18 09:33:16 SealedSecret default/mysecret has gone, deleting Secret
2017/09/18 09:33:16 Error updating default/mysecret, will retry: secrets "mysecret" not found
2017/09/18 09:33:16 SealedSecret default/mysecret has gone, deleting Secret
2017/09/18 09:33:16 Error updating default/mysecret, giving up: secrets "mysecret" not found
E0918 09:33:16.488086       1 controller.go:162] secrets "mysecret" not found
```

**Comment by arapulido** [comment]
I guess this is expected behaviour, but maybe we should recreate the secret if deleted and there is a sealedsecret. What do we think the UX for this should be?

**Comment by anguslees** [comment]
We should just ignore "not found" at this point in the code, as we just want to delete the Secret and don't really care "how" the secret was deleted.

Recreating the Secret if you delete it sounds like a separate issue, and is worth discussing.  I kind of feel like if you deleted the secret then you probably meant to for some reason and we don't need to "optimise" this.  Currently I think the Secret will be recreated when the controller restarts (since it won't be able to tell the difference between that and the regular new-SealedSecret case).  I would have said that was just fine for such a rare/ambiguous situation, but this was also one of only two questions asked of sebgoa after his demo at k8s community meeting - which makes me wonder if there's some importance here that I'm missing..
